cmake_minimum_required(VERSION 3.8)
project(recruitment_sim_description)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_python REQUIRED)
find_package(gazebo REQUIRED)
find_package(rclcpp REQUIRED)
find_package(recruitment_sim_interfaces REQUIRED)
find_package(recruitment_sim_robot_base REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(std_msgs REQUIRED)
include_directories(${GAZEBO_INCLUDE_DIRS})
link_directories(${GAZEBO_LIBRARY_DIRS})
set(CMAKE_INSTALL_RPATH "$ORIGIN")
add_library(RecruitmentSimRuntime SHARED plugins/classic/Runtime.cc)
add_library(RecruitmentSimRobot SHARED plugins/classic/Robot.cc)
add_library(RecruitmentSimRefereeSimulation SHARED plugins/classic/World.cc)
add_library(RecruitmentSimSensors SHARED plugins/classic/Sensors.cc)
foreach(target RecruitmentSimRuntime RecruitmentSimRobot RecruitmentSimRefereeSimulation RecruitmentSimSensors)
  ament_target_dependencies(${target} rclcpp recruitment_sim_interfaces recruitment_sim_robot_base sensor_msgs nav_msgs geometry_msgs std_msgs)
  target_link_libraries(${target} ${GAZEBO_LIBRARIES})
  if(NOT target STREQUAL "RecruitmentSimRuntime")
    target_link_libraries(${target} RecruitmentSimRuntime)
  endif()
endforeach()
install(TARGETS RecruitmentSimRuntime RecruitmentSimRobot RecruitmentSimRefereeSimulation RecruitmentSimSensors LIBRARY DESTINATION plugins)
install(DIRECTORY resource DESTINATION share/${PROJECT_NAME})
ament_python_install_package(${PROJECT_NAME})
ament_environment_hooks("${CMAKE_CURRENT_SOURCE_DIR}/env-hooks/gazebo.dsv.in")
if(BUILD_TESTING)
  find_package(ament_cmake_gtest REQUIRED)
  ament_add_gtest(test_direction_noise test/test_direction_noise.cpp)
  target_link_libraries(test_direction_noise ${GAZEBO_LIBRARIES})
endif()
ament_package()
