<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>recruitment_sim_bringup</name>
  <version>0.1.0</version>
  <description>Bringup, world and bridge configuration for the recruitment simulation.</description>
  <maintainer email="maintainers@example.com">Recruitment Simulation Maintainers</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>recruitment_sim_description</exec_depend>
  <exec_depend>recruitment_sim_player_web</exec_depend>
  <exec_depend>recruitment_sim_robot_base</exec_depend>
  <exec_depend>recruitment_sim_referee_system</exec_depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>rosgraph_msgs</depend>
  <depend>recruitment_sim_interfaces</depend>
  <exec_depend>rviz2</exec_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
